[package]
name = "yew-plotly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotly = { version = "=0.8.1", features = ["wasm"] }
wasm-bindgen = "0.2.83"
yew = "0.19.3"
